[package]
name = "ur2_005_errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# I thought you might want this for your library...
thiserror = "1.0"
# ...and this for your binary
anyhow = "1.0"
